ALTER TABLE bilietas
ADD FOREIGN KEY (Seanso_Nr) REFERENCES seansas(Nr)
	ON DELETE CASCADE
	ON UPDATE CASCADE
;

ALTER TABLE seansas
ADD FOREIGN KEY (Filmo_Pavadinimas) REFERENCES filmas(Pavadinimas)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
ADD	FOREIGN KEY (Sales_Nr) REFERENCES sale(Nr)
	ON DELETE CASCADE
	ON UPDATE RESTRICT --RESTRICT, SET NULL, SET DEFAULT
;
